name: Develop Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.1'

      - name: Install Dependencies
        run: bundle install
 
      - name: Run RuboCop
        run: gem install rubocop && bundle exec rubocop

      - name: scan for vulnerabilities
        run:  gem install bundler-audit && bundle audit check --update

      - name: Run Unit Tests
        run: bundle exec rspec

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --pull --rm -f "Dockerfile" -t ${{ secrets.DOCKER_USERNAME }}/ruby:develop "."
          docker push ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop
    
